### PR TITLE
Fix false positive in Notifications test for Chrome on Android (fixes #1660)

### LINKED ISSUE #1660: Notification feature detect gives false positives Chrome 45 on Android
Feature detect for Web Notifications is bit of a mess in Chrome on Android :-/

See https://github.com/alexgibson/notify.js/issues/38 for details.

### PR DESCRIPTION
**Pull request by alexgibson**
Please see #1660 for details. Note I don't actually have Chrome for Android to test on. I'm basing the change on this article: https://developers.google.com/web/updates/2015/05/Notifying-you-of-notificiation-changes

### CODE REVIEW

File: feature-detects/notification.js [hunk 1]
```diff
@@ -18,5 +24,22 @@
...
+    // if permission is already granted, assume support
+    if (window.Notification.permission === 'granted') {
+      return true;
+    }
+
+    try {
+      new window.Notification('');
+    } catch (e) {
+      if (e.name === 'TypeError') {
+          return false;
```
Comment (ryanseddon) [inline feature-detects/notification.js]: two space indent

File: feature-detects/notification.js [hunk 2]
```diff
@@ -18,5 +24,22 @@
...
+      }
+    }
+    return true;
```
Comment (ryanseddon) [inline feature-detects/notification.js]: New line above

**Comment by ryanseddon** [comment]
Just tested on a nexus 6 with chrome 45 and it returns no support for notifications with your updated test. Is this correct?

Test case: http://output.jsbin.com/memunosofe/quiet

realdroid_google_nexus_6

**Comment by alexgibson** [comment]
Thanks @ryanseddon - yes this is correct, it should return false as only push notifications are now supported in Chrome on Android. Will update these nits shortly.

**Comment by alexgibson** [comment]
@ryanseddon updated thanks

**Comment by patrickkettner** [comment]
@alexgibson could you fix the style issue?

**Comment by alexgibson** [comment]
@patrickkettner updated

**Comment by alexgibson** [comment]
Note: The AppVeyor failure for Node v0.10 looks unrelated to this change.

**Comment by ryanseddon** [comment]
Yep appveyor seems to fail sometimes for other unrelated reasons.
