### PR TITLE
fixes for the flash detect

### LINKED ISSUE #1413: Modernizr v3 flash detect always returning {block: true} in Chrome
Hey,

When using the Flash feature detection in Modernizr v3, `Modernizr.flash` always has the value `{blocked: true}` when using Chrome (or equivalent like Opera). 

Flash is correctly enabled in the browser and the page in question includes Modernizr in the `<head>`. If the same page is tested in Firefox, `Modernizr.flash` has the value `true`.

The code that is causing the issue appears to be https://github.com/Modernizr/Modernizr/blob/master/feature-detects/flash.js#L54. `<embed>` does not possess the property `Pan` at the point that Modernizr performs its check. 

Shifting the code inside the `setTimeout` does not help, nor does increasing the timeout. However, if you execute the following code in the console after the page has fully loaded it will return `true`

```javascript
var embed = document.createElement('embed');
embed.type = 'application/x-shockwave-flash';
document.body.appendChild(embed);
console.log('Pan?', ('Pan' in embed));
```

I'm using Chrome v36, Mac OSX.

### LINKED ISSUE #1432: flash detection throws an error in IE
The feature-detect/flash.js script throws an error in all version of IE.

this happens at lin 82 :
if (body.fake) {
    body.parentNode.removeChild(body);
}

the error is : SCRIPT5007: Unable to get property 'removeChild' of undefined or null reference
this happens because the parentNode property is empty.

i've 'fixed' this in my local version like this : 
if (body.fake && body.parentNode) {
    body.parentNode.removeChild(body);
}

Although i think this is not the correct way to actually fix it...
just wanted to report the error and see if anybody knows how to correctly fix this issue.

ps: this is on the master branch

### PR DESCRIPTION
**Pull request by patrickkettner**
fixes #1413, also fixes #1432

### CODE REVIEW

File: feature-detects/flash.js [hunk 1]
```diff
@@ -77,11 +85,18 @@ define(['Modernizr', 'createElement', 'docElement', 'addTest', 'getBody'], funct
           }
         }
 
-        // If we’re rockin’ a fake body, clean it up
-        if (body.fake) {
+        // If we’re rockin’ an attached fake body, clean it up
+        if (body.fake && body.parentNode) {
```
Comment (noahgrant) [inline feature-detects/flash.js]: Not sure if it stems from this, and I can create an issue for it, but my Modernizr build from gulp-modernizr (after a fresh npm install yesterday) did not remove the extra body element, so we had two `<body>`s in our app!  I had to set modernizr to "3.0.0-pre" in our package.json, since customizr uses the master branch from github.

Comment (patrickkettner) [inline feature-detects/flash.js]: would you be able to test this commit and the commit before?

Comment (noahgrant) [inline feature-detects/flash.js]: Confirmed—installing Modernizr at commit [https://github.com/Modernizr/Modernizr/commit/a6ca9d9f240071107249241f83223c4185151875](a6ca9d) works as normal, but Modernizr at commit [https://github.com/Modernizr/Modernizr/commit/1db6eee599e40848b5f571f3c09f32b64b926d82](1db6ee) leaves the extra body element in.

Comment (patrickkettner) [inline feature-detects/flash.js]: what browser? are you loading in the head body, or bottom?

Comment (noahgrant) [inline feature-detects/flash.js]: happens in chrome 39, firefox 32, and safari 8, with the script in the head.

Comment (niksy) [inline feature-detects/flash.js]: Seeing the same thing, so I created [pull request](https://github.com/Modernizr/Modernizr/pull/1506) for this.
